In [9]:
import numpy as np

In [10]:
#Koordinate poznatih 7 temena (na osnovu Paint-a)
p1 = np.array([493,495])
p2 = np.array([270,687])
p3 = np.array([129,553])
p5 = np.array([524,357])
p6 = np.array([268,524])
p7 = np.array([106,405])
p8 = np.array([359,294])


In [11]:
def affToHom(point):
    return np.append(point,1)

In [31]:
def homToAff(point):
    return np.round(point[:2])

In [12]:
p1

array([493, 495])

In [13]:
p1H = affToHom(p1)

In [15]:
p2H = affToHom(p2)
p3H = affToHom(p3)
p5H = affToHom(p5)
p6H = affToHom(p6)
p7H = affToHom(p7)
p8H = affToHom(p8)

In [ ]:
def afinize(point):
    return point/point[2] 

In [18]:
def vanishingPoints(point1, point2, point3, point4):
    l1 = np.cross(point1,point2)
    l2 = np.cross(point3, point4)
    return afinize(np.cross(l1,l2))

In [ ]:
#Racunamo tacku nedogleda za svake dve 'paralelne' prave, 
#i onda za nasu izabranu tacku uzimamo njihov prosek
X1 = vanishingPoints(p1H, p2H, p5H, p6H)
X2 = vanishingPoints(p1H, p2H, p7H, p8H)
X3 = vanishingPoints(p5H, p6H, p7H, p8H)

Xvb = (X1 + X2 + X3)/3

In [21]:
Y1 = vanishingPoints(p2H, p3H, p6H, p7H)
Y2 = vanishingPoints(p2H, p3H, p5H, p8H)
Y3 = vanishingPoints(p6H, p7H, p5H, p8H)

Yvb = (Y1 + Y2 + Y3)/3

In [22]:
Z1 = vanishingPoints(p3H, p7H, p2H, p6H)
Z2 = vanishingPoints(p3H, p7H, p1H, p5H)
Z3 = vanishingPoints(p2H, p6H, p1H, p5H)

Zvb = (Z1 + Z2 + Z3)/3

In [ ]:
#Nedostajuce teme p4 racunamo kao presek prava iz tacaka nedogleda sa vec poznatim odgovarajucim temenima
#Izracunamo svaki od njih i opet uzimamo njihov prosek kao konacnu tacku
p41 = vanishingPoints(Xvb, p3H, Zvb, p8H) #Sa slike je jasno da je prava koja nam treba Xvb i p3 itd.
p42 = vanishingPoints(Xvb , p3H, Yvb, p1H)
p43 = vanishingPoints(Yvb, p1H, Zvb, p8H)

p4 = (p41 + p42 + p43)/3

In [26]:
p4

array([351.25535596, 420.21549429,   1.        ])

In [ ]:
#Konacno resenje je [351,420] sto ima smisla kada se uporedi sa ostalih 7 temena
homToAff(p4)

array([351., 420.])